default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: technology_pyramid_development

test:
  <<: *default
  database: technology_pyramid_test

production:
  <<: *default
  database: technology_pyramid_production
  username: technology_pyramid
  password: <%= ENV['TECHNOLOGY_PYRAMID_DATABASE_PASSWORD'] %>
